### ISSUE TITLE
Sourcemaps broken

### ISSUE THREAD

**Issue by codepunkt** [csstools/postcss-normalize#1]
Wenn using this with `postcss-loader` and `webpack`, source maps are broken regardless of the order i put this in comparison to the other postcss plugins. as soon as i stop using it, sourcemaps are fine.

``` javascript
postcss: function() {
  return [
    require('postcss-normalize'),
    require('autoprefixer-core'),
    require('csswring')
  ];
}
```

**Comment by madeleineostoja** [comment]
hrmm not sure what’s going on here. Will have to look more into how PostCSS handles sourcemaps with `.prepend()`, and how webpack does things.

**Comment by codepunkt** [comment]
I'm not sure either. Would be nice if you looked into it - i'm afraid i don't find the time atm :(

**Comment by madeleineostoja** [comment]
FYI this package is being deprecated (see #9). Use postcss-import instead.
