### ISSUE TITLE
Transfer repository

### ISSUE THREAD

**Issue by jonathantneal** [csstools/postcss-normalize#10]
Hey @seaneking, would you mind transferring this repository over to me? I maintain normalize.css and I would like to continue servicing this repo.

**Comment by jonathantneal** [comment]
Oh! More importantly, I would need access to the npm package: https://www.npmjs.com/package/postcss-normalize

**Comment by madeleineostoja** [comment]
Sure thing 👍

**Comment by madeleineostoja** [comment]
Done. Also added you as an owner to the NPM package.

Thanks for taking the reigns!
