### ISSUE TITLE
Will it detect browserlist file?

### ISSUE THREAD

**Issue by jitendravyas** [csstools/postcss-normalize#11]

**Comment by jonathantneal** [comment]
@jitendravyas, I believe so. All the magic comes from browserslist in this line https://github.com/jonathantneal/postcss-normalize/blob/master/index.js#L13-L15

@ai, is this correct usage?

**Comment by ai** [comment]
Yeap, it will autodetect file.

@jonathantneal everything is good :+1:

**Comment by jonathantneal** [comment]
Thanks!
