### ISSUE TITLE
_autoprefixerPrefix error with postcss 6

### ISSUE THREAD

**Issue by shrpne** [csstools/postcss-normalize#13]
Cannot read property '_autoprefixerPrefix' of undefined
This error occurs with postcss v6. With postcss v5 everything works fine.

**Comment by jonathantneal** [comment]
Version 2 now supports PostCSS 6. Would you try again?

**Comment by shrpne** [comment]
Seems it is still not fixed for me.
I updated package.json, deleted npm, reinstalled modules and error still exists.
(There was deprecation warning about Node.raws it was fixed after update)

I use Node v7 if it matters

**Comment by jonathantneal** [comment]
Thanks for the update. I’m wondering if it’s another plugin in your stack. What other plugins are you using? I only ask because this project does not use Autoprefixer, and your error indicates something with Autoprefixer.

**Comment by shrpne** [comment]
I'm using only postcss-normalize and autoprefixer.
I made a little test. It is strange, but everything works fine, if normalize goes after autoprefixer.
But if normalize goes first, error occurs.
Like this:
```
.pipe(postcss([
    postcssNormalize(),
    autoprefixer()
]))
```

**Comment by ai** [comment]
I have same issue. Seems like AST is broken after `postcss-normalize`. Maybe `jsonToAst` have issues?

**Comment by jonathantneal** [comment]
Testing this now.

**Comment by ai** [comment]
@jonathantneal what I should test? `master`?

**Comment by jonathantneal** [comment]
This should be resoled in 2.0.1.

Test: https://github.com/jonathantneal/postcss-tests/blob/master/postcss-normalize-test-00

Test Plugins: https://github.com/jonathantneal/postcss-tests/blob/master/postcss-normalize-test-00/test.js#L8-L9

**Comment by ai** [comment]
Thanks for fast fix, everything works now
