### ISSUE TITLE
Anyway to have single insertion across multiple compiles?

### ISSUE THREAD

**Issue by jackysee** [csstools/postcss-normalize#18]
I'm using vue, configured the `vue-loader` to render the `.vue` file's `<style>` section to use postcss. 

As each component get its own `<style>`, this plugin would inject itself multiple times. I would like to have a configuration such that it only inject when `@import-normalize` is found. So that I can control it to appear only on top-level component. Like:
```
plugins : [ 
//...
    require('postcss-normalize')({ injectByImportOnly: true })
]
```

I can workaround it by download the `normalize.css` and use `postcss-import`, but it that way I cannot benefit from the `browserlist` to output a smaller file to my targeted browser.

**Comment by madeleineostoja** [comment]
See https://github.com/jonathantneal/postcss-normalize/issues/14

**Comment by madeleineostoja** [comment]
@jonathantneal Perhaps docs need to be clearer on this?

**Comment by jonathantneal** [comment]
@jackysee, that’s a great idea, and I may release a new major version that makes injection by `@import-normalize` the **default**.

**Comment by jonathantneal** [comment]
Done via v4.0.0. Published!
