### ISSUE TITLE
Why not use opinionated?

### ISSUE THREAD

**Issue by niccai** [csstools/postcss-normalize#19]
I think not including some of the opinionated CSS in this project is not ideal (opinion :).  I would think that most consumers of normalize would use the default that includes these.  Can you explain the argument in not including the body margin fix for instance?  Currently, these projects include it by default:

https://github.com/necolas/normalize.css
https://github.com/JohnAlbin/normalize-scss

**Comment by jonathantneal** [comment]
Hi @niccai, thanks for asking. First, it’s a requirement of the project:

> PostCSS Normalize lets you use the parts of normalize.css you need, based on your project’s browserlist.

No one _needs_ opinionated styles, and no browserslist can target which browsers require opinionated styles. Also, requiring developers to add `body { margin: 0 }` is a fairly _small_ barrier of entry. Also, once browerslists are involved, including them might give a false impression that browsers _should_ receive these styles.

This is why the documentation states:

> PostCSS Normalize uses the non-opinionated version of normalize.css.

And it looks like JohnAlbin’s SCSS version [removes the opinionated rules](https://github.com/JohnAlbin/normalize-scss/issues/107) or at least only keeps the ones he likes.

**Comment by niccai** [comment]
Sounds good.  I expect I won't be the last person to raise this point.  FWIW, I think body margin 0 is expected by most. Perhaps make the line about opinionated styles more prominent in the README?  I saw it - but only after I intro'd a bug in development.

**Comment by jonathantneal** [comment]
Understood. I’m unsure how to include such a note. I’ll see how things resolve in the normalize.css repo. Track what’s going on with the opinionated rules in normalize.css. It seems they weren’t really tested or added back in consistently.
