### ISSUE TITLE
Support for multi CSS files would be useful e.g. when use multiple CSS chunks

### ISSUE THREAD

**Issue by swernerx** [csstools/postcss-normalize#20]
I'd like to leave a feature request for supporting an option which only inserts when the algorithm find the `@import-normalize;` inside the file. Reason for this: In our current setup we process multiple CSS files with one common setup from inside a complex Webpack configuration. When using this plugin right now it appends the whole "matched" normalize rules to each individual output stylesheet which adds some duplication to our bundles.

**Comment by jonathantneal** [comment]
Done via v4.0.0. Published!

**Comment by swernerx** [comment]
Perfect!

**Comment by swernerx** [comment]
Added to: https://github.com/sebastian-software/edge-postcss/releases/tag/0.6.0
