### ISSUE TITLE
Support @import "node_modules/postcss-normalize/lib/normalize.css"

### ISSUE THREAD

**Issue by sntran** [csstools/postcss-normalize#27]
Let me explain:

During development, I use the CSS file as-is, without any pre- or post-processor. I only run `postcss` and `postcss-normalize` when building for production.

In order to have `normalize.css` in development, I needs to be able to import it from `node_modules`. I can't use `@import-normalize` nor `@import "postcss-normalize".

It would be great if this plugin can detect the `@import`from path **containing** "node_modules/postcss-normalize/lib/normalize.css" besides `@import-normalize` so I can see the normalized styles in both environments.

**Comment by stramel** [comment]
@sntran Move the `@import-normalize` to another file without any `@import`s then use `@import <path/to/file>` to load it in.

**Comment by jonathantneal** [comment]
I would follow what @stramel has said, unless we can modify those import plugins (which is very unlikely).

**Comment by sntran** [comment]
Sorry for being an idiot, but I don't see how @stramel suggested would work? During development, I don't run my file through `postcss`. Having a file with `@import-normalize` would not resolve to anything, and I won't see normalize stuffs in development.
