### ISSUE TITLE
normalize dependency missing for npm3

### ISSUE THREAD

**Issue by pr1ntr** [csstools/postcss-normalize#3]
NPM3 doesn't automatically resolve peer dependencies. Should either package the dep or not explicitly require it to be in the package.

**Comment by pr1ntr** [comment]
Maybe latest isn't published to npm?

**Comment by pr1ntr** [comment]
yeah my bad. Could you publish latest to npm please?

**Comment by madeleineostoja** [comment]
derp yep sorry, fixed in https://github.com/seaneking/postcss-normalize/commit/2c1af7f387d554aae5f991d4a583cb53afd8a501
