### ISSUE TITLE
Why is normalize overriding my styles?

### ISSUE THREAD

**Issue by JamesTheHacker** [csstools/postcss-normalize#32]
I'm trying to use [postcss-normalize][1] with PostCSS. Anywhere I place the plugin in the list causes it to override my styles. I have `forceImport` set to true so I don't need to import it anywhere.

Here's my `.postcssrc`:

    {
      "modules": false,
      "plugins": {
        "postcss-normalize": {
          forceImport: true,
        },
        "postcss-import": {},
        "postcss-nesting": {},
        "postcss-preset-env": {
          "autoprefixer": {
            "grid": true
          }
        },
        "postcss-color-mod-function": {},
        "postcss-font-magician": [
          {
              "variants": {
                  "Open Sans": {
                      "300": [],
                      "400": [],
                      "700": []
                  },
                  "Arvo": {
                    "400": [],
                    "700": []
                }
              },
              "foundries": ["google"]
          }
        ]
      }
    }

  [1]: https://github.com/csstools/postcss-normalize

I'm also using ParcelJS and I import my styles in `index.js` like so:

    import "./css/layout.css"
    import "./css/base.css"
    import "./css/fonts.css"
    import "./css/theme.css"
    
    import header from "./modules/luxbar"
    import jumbo from "./modules/jumbo"
    import partners from "./modules/partners"
    import instructions from "./modules/instructions"
    import about from "./modules/about"
    import faq from "./modules/faq";
    import contact from "./modules/contact"
    import testimonials from "./modules/testimonials";
    
    header();
    jumbo();           
    partners();        
    instructions();
    about();           
    testimonials()
    faq('.faq-list');   
    contact();   

A module looks like this:

    import $ from 'jquery'
    import slick from 'slick-carousel'
    import "./base.pcss"
    
    export default () => {
        $('.partners__carousel').slick({
            autoplay: true,
            speed: 300,
            arrows: false,
            mobileFirst: true,
            centerMode: true,
            slidesToShow: 2,
            slidesToScroll: 1,
            buttons: false,
        })
    }

The CSS is imported in the `index.js` for that module.

Any ideas how to solve this? Why is normalize overriding my own styles?

**Comment by jonathantneal** [comment]
What happens if you move postcss-normalize to the _end_ of your plugin list? Does it correct the output?

If it resolves your issue, this is a workaround, and the issue is a limitation of PostCSS and the PostCSS Import plugin.

**Comment by JamesTheHacker** [comment]
Tried that still no luck. Here's the entire error:

```
base.css?./node_modules/css-loader??ref--4-1!./node_modules/postcss-loader/src:1 Uncaught Error: Module build failed (from ./node_modules/postcss-loader/src/index.js):
SyntaxError

(46:31) Expected a color

 [90m 44 | [39m    &[33m:[39mfocus [33m{[39m
 [90m 45 | [39m        border[33m:[39m 1px solid [36mvar[39m[36m(--electric-blue)[39m[33m;[39m
[31m[1m>[22m[39m[90m 46 | [39m        background[33m:[39m [36mcolor-mod[39m[36m([39m[36mvar[39m[36m(--electric-blue)[39m [36mblend[39m[36m(red 50%)[39m[36m)[39m !important[33m;[39m
 [90m    | [39m                              [31m[1m^[22m[39m
 [90m 47 | [39m        outline[33m:[39m 1px solid [36mvar[39m[36m(--electric-blue)[39m[33m;[39m
 [90m 48 | [39m    [33m}[39m


    at eval (base.css?./node_modules/css-loader??ref--4-1!./node_modules/postcss-loader/src:1)
    at Object../node_modules/css-loader/index.js?!./node_modules/postcss-loader/src/index.js!./src/css/base.css (index.js:154)
    at __webpack_require__ (index.js:20)
    at eval (base.css:2)
    at Object../src/css/base.css (index.js:691)
    at __webpack_require__ (index.js:20)
    at eval (index.js:10)
    at Module../src/index.js (index.js:736)
    at __webpack_require__ (index.js:20)
    at eval (webpack:///multi_(:1313/webpack)-dev-server/client?:2:18)
(anonymous) @ base.css?./node_modules/css-loader??ref--4-1!./node_modules/postcss-loader/src:1
./node_modules/css-loader/index.js?!./node_modules/postcss-loader/src/index.js!./src/css/base.css @ index.js:154
__webpack_require__ @ index.js:20
(anonymous) @ base.css:2
./src/css/base.css @ index.js:691
__webpack_require__ @ index.js:20
(anonymous) @ index.js:10
./src/index.js @ index.js:736
__webpack_require__ @ index.js:20
(anonymous) @ client:2
0 @ index.js:964
__webpack_require__ @ index.js:20
(anonymous) @ index.js:84
(anonymous) @ index.js:87
client:156 [WDS] Errors while compiling. Reload prevented.
```

I'm wondering why those colors look like that?

**Comment by JamesTheHacker** [comment]
And the variable is available because I'm using it in the line above and the outline is the color expected (--electric-blue).

**Comment by JamesTheHacker** [comment]
That solved it.
