### ISSUE TITLE
normalize disapears after second compilation

### ISSUE THREAD

**Issue by joelmoss** [csstools/postcss-normalize#34]
I've included this lib and the first time webpack builds, normalize is included fine, but after a second compile (after a css change somewhere else), normalize is no longer imported.

```
@import-normalize;
```

Any ideas?

**Comment by diverent2** [comment]
Can you share the webpack- and postcss-config file you´ve used that lead to this issue?
Are you using the `force`option?
```
postcssNormalize({
  forceImport: true
});
```

**Comment by germn** [comment]
I can confirm problem at least for recompile with webpack-dev-server.

Example config can be found [here](https://github.com/germn/webpack_dev_server_issue_1623/blob/1e33d537ac46b1f1ddc8031a7d398e5ffd09c324/webpack/common.js#L57).

To reproduce:
- `git clone https://github.com/germn/webpack_dev_server_issue_1623`
- `cd webpack_dev_server_issue_1623`
- `npm install`
- `npm run static-dev-server`
- check `static_meta/tags.html` to see css url
- change `static_src/app/index.css` to recompile
- check updated css url to see normalize section disappered

Issue appears regardless of using `forceImport`.

**Comment by macdaddyaz** [comment]
I am experiencing the same behavior running through the PostCSS Express middleware.

app.js:

```js
app.use('/css/:style.css', postcssMiddleware({
  src(req) {
    const filename = req.params.style;
    return path.join(__dirname, 'public/stylesheets', `${filename}.pcss`);
  },
  plugins: [
    postcssNormalize({ browsers: 'last 2 versions' }),
  ],
}));
```

styles.pcss:

```pcss
@import-normalize;

/* My custom rules */
```

First request to `http://localhost:3000/css/styles.css` has the normalize.css rules before the custom rules. Subsequent requests do not (regardless of whether the source has changed).

**Comment by jonathantneal** [comment]
I think this will be better handled in the next release, when I am more conservatively attaching normalize.css.

**Comment by jonathantneal** [comment]
Resolved in v8 😄
