### ISSUE TITLE
Does not honor "browsers" configuration option

### ISSUE THREAD

**Issue by benjaminblack** [csstools/postcss-normalize#35]
Node v11.3.0.

Steps to reproduce:

0. Create test directory

1. `npm init -y`

2. `npm install --save-dev postcss-normalize`

3. create `main.postcss`:

```
@import-normalize;
```

4. create postcss build script `build.js`:

```
const fs = require('fs');
const postcssNormalize = require('postcss-normalize');

(async () => {
    const precss = fs.readFileSync('./main.postcss');

    const {css} = await postcssNormalize.process(precss, { browsers: 'last 2 versions' });

    console.log(css);
})();
```

Run `node build.js`. Note that output includes everything (is not restricted to browserslist.)

**Comment by jonathantneal** [comment]
I will test this later today with the upcoming release.

**Comment by jonathantneal** [comment]
I have tests in `.tape.js` for the next release that show this to be working. I also realize that in your example you were sticking `browsers` in the process configuration. See https://github.com/csstools/postcss-normalize#browsers

**Comment by benjaminblack** [comment]
Your documentation page has this example, which is what I was attempting to follow:

```
import postcssNormalize from 'postcss-normalize';

postcssNormalize.process(YOUR_CSS /*, processOptions, pluginOptions */);
```

This syntax does not work for me.

Passing it as a plugin option also does not work for me:

`postcssNormalize.process(precss, {}, { browsers: 'last 2 versions' });`
