### ISSUE TITLE
Permission to copy content from readme

### ISSUE THREAD

**Issue by mrchief** [csstools/postcss-normalize#36]
I'm trying to add postcss-normalize natively in create-react-app [(PR)](https://github.com/facebook/create-react-app/pull/5810). I need to add documentation around it and I'd like to reuse parts of readme text in there if that's OK with the authors/collaborators?

Also, once the PR gets merged, folks would no longer have to go through [special instructions](https://github.com/csstools/postcss-normalize/blob/master/INSTALL.md#create-react-app), so that part may need an update.

**Comment by jonathantneal** [comment]
Yes, you have all the permission in the world. Sorry for the delay. It looks like it has been added, so I will tentatively close this.

**Comment by mrchief** [comment]
Yes. So this section is obsolete: https://github.com/csstools/postcss-normalize/blob/master/INSTALL.md#create-react-app. Do you want me to send a PR to update the readme?
