### ISSUE TITLE
not working with postcss-cli json config

### ISSUE THREAD

**Issue by Yimiprod** [csstools/postcss-normalize#50]
with this config

```js
{
  plugins: {
    'postcss-normalize': {},
  },
}
```

putting `@import-normalize;` isn't working, no normalize is imported, and in the output we still have it, not transformed.

**Comment by WahidN** [comment]
Any solutions for this?

**Comment by romainmenke** [comment]
Sorry, not enough info here.
Can you provide a minimal reproduction?

If you do provide a minimal repro I will re-open this issue.
