### ISSUE TITLE
Compatibility with PostCSS 8

### ISSUE THREAD

**Issue by jonnitto** [csstools/postcss-normalize#52]
**Thanks for your PostCSS plugin!** 

As you probably know, [PostCSS 8] was released a few days ago. It would be great if you could make this plugin compatible with the latest version. The creators of the project have even released this [migration guide].

[PostCSS 8]: https://github.com/postcss/postcss/releases/tag/8.0.0
[migration guide]: https://evilmartians.com/chronicles/postcss-8-plugin-migration

**Comment by KurtMar** [comment]
@jonathantneal Do you have any plans to support PostCSS 8 in `postcss-normalize` and `postcss-browser-comments`? These two packages seem to be holding back `create-react-app` from upgrading to PostCSS 8 and thus holding quite a few people back in the react community. More details about this here: https://github.com/facebook/create-react-app/issues/9664#issuecomment-787472229

Looking at the installation instructions for Tailwind with create-react-app paints a good picture how this has far reaching consequences: https://tailwindcss.com/docs/guides/create-react-app

All I'm asking is a heads up if this is not going to happen or if there's help wanted.

Thanks for all your hard work for the community so far!

**Comment by jonathantneal** [comment]
Time. It’s all just a matter of time. I take runs at completing this, but rarely have enough time to get them across to publish

**Comment by KurtMar** [comment]
Cheers Jonathan for the update! In other words, if there are people in the community reading this with a good understanding of the libraries and can perhaps even contribute on company time, then PRs would be welcomed?

**Comment by jonathantneal** [comment]
Yes, so very welcomed.

**Comment by OmerWow** [comment]
@jonathantneal what progress have you made those far? have any commits yet?
I barely know anything about these libraries but I'm pretty desperate, if you have any progress I'll give it a look.
As a Tailwind dev and now that's TailwindJIT is out - this sucks lol

**Comment by Bluefitdev** [comment]
True, i really want to get this up and going but not sure if i did this right for this plugin

**Comment by jonathantneal** [comment]
This has been resolved in https://github.com/csstools/postcss-normalize/tree/10.0.0

**Comment by Bluefitdev** [comment]
You're awesome! @jonathantneal
