### ISSUE TITLE
Should postcss-browser-comments be forked/replaced?

### ISSUE THREAD

**Issue by radiosilence** [csstools/postcss-normalize#54]
It seems quite silly to rely on a library with only 8 stars that hasn't been updated in over two years.

Perhaps it would be simpler to fork it, update the fork to be compatible with postcss@8, and rely on that fork. 

**The whole create-react-app ecosystem is currently being held back by this package.**

**Comment by jonathantneal** [comment]
This has been resolved in https://github.com/csstools/postcss-normalize/tree/10.0.0

**Comment by radiosilence** [comment]
Thanks!
