### ISSUE TITLE
Use PostCSS 8 events

### ISSUE THREAD

**Issue by ai** [csstools/postcss-normalize#55]
Using `Once` is a bad practice, because it doesn't guarantee plugin comparability (for instance, if `@postcss-normalize` will be inserted by mixin).

For this plugin `AtRule` is much better event.

**Comment by romainmenke** [comment]
I tried to migrate away from `Once`, but this package uses `reduce` all over and I refuse to refactor such code : https://github.com/csstools/postcss-normalize/blob/main/src/lib/postcssNormalize.js#L51-L94

There is way too much complexity here, way more than needed and I would rather keep the code as it currently is.

If someone is willing to take the time to untangle this code and ensure that there isn't any behavior change then I will gladly accept a PR that refactors to use the `AtRule` event.
