### ISSUE TITLE
Node 10 support

### ISSUE THREAD

**Issue by mrmckeb** [csstools/postcss-normalize#56]
Hi there, we're upgrading dependencies in CRA and we see that you've dropped support for Node 10, which we're still supporting today (although we plan to deprecated).

It looks like this isn't an issue for PostCSS 8, so I wondered if it was that changes you made mean this no longer works in Node 10.x, or if this was around support only?

If it's the latter, would you consider reverting that - or if not, would it be OK if we fork this until we drop Node 10 if that's OK?

**Comment by romainmenke** [comment]
We dropped support for everything up to node 18.
Not going to relax the minimum version
