### ISSUE TITLE
Add modern-normalize

### ISSUE THREAD

**Issue by loctran016** [csstools/postcss-normalize#57]
Well, (modern-normalize)[https://github.com/sindresorhus/modern-normalize] is smaller than the old one and it's currently used by tailwindcss

**Comment by jonathantneal** [comment]
Unfortunately, `modern-normalize` is an attempt to fix a different version of `normalize.css` that I no longer have access to. I don’t want to discourage anyone else making another normalize, but that project doesn’t fix bugs in current browsers and more closely resembles `sanitize.css`.
